config/routes.rb
Rails.application.routes.draw do
  resources :passengers
  resources :bookings
  resources :flights
  resources :charges do
    member do
      get 'success'
    end
  end

  root 'flights#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :from_airport, class_name: 'Airport'
  belongs_to :to_airport, class_name: 'Airport'
  has_many :bookings, dependent: :destroy

  def self.search(search)
    if search.empty?
      nil
    elsif search
      flights = Flight.all
      flights = flights.where('from_airport_id = ?', search[:from_airport_id]) if search[:from_airport_id]
      flights = flights.where('to_airport_id = ?', search[:to_airport_id]) if search[:to_airport_id]
      flights = flights.where(takeoff: Date.parse(search[:takeoff]).all_day) if search[:takeoff]

    end
    flights
  end
end

app/controllers/flights_controller.rb
require 'active_support/core_ext'

class FlightsController < ApplicationController
  before_action :set_flight, only: %i[show edit update destroy]

  # GET /flights
  # GET /flights.json
  def index
    @airport_options = Airport.all.map { |u| [u.code, u.id] }
    @date_options = Flight.all.map { |u| u.takeoff.to_date }.uniq

    return unless params[:flight]

    params[:flight].reject! { |_, v| v.blank? }
    @flights = Flight.search(params[:flight])
  end

  # GET /flights/1
  # GET /flights/1.json
  def show; end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit; end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1
  # PATCH/PUT /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_flight
    @flight = Flight.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def flight_params
    params.require(:flight).permit(:from_airport_id, :to_airport_id, :takeoff, :num_passenger)
  end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_form.html.erb
<%= form_with(model: flight) do |form| %>
  <% if flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
        <% flight.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/flights/_results.html.erb
<h1 class="title">results</h1>
<table class="table">
  <thead>
    <th>Departure</th>
    <th>Arrival</th>
    <th>Take off</th>
    <th>Duration</th>
    <th>Select for booking</th>
  </thead>

  <tbody>

    <%= form_for :booking, url: new_booking_path, method: "GET", local: true do |f| %>
      <%= f.hidden_field :num_passenger, value: params[:flight][:num_passenger]%>

      <% @flights.each do |flt|%>
        <tr>
          <td>
            <%=flt.from_airport.city%> <%=flt.from_airport.state%> <%=flt.from_airport.code%>
          </td>
          <td>
          <%=flt.to_airport.city%> <%=flt.to_airport.state%>  <%=flt.to_airport.code%> 
          </td>

          <td>
            <%=flt.takeoff%>
          </td>

          <td>
            <%=flt.duration / 60.to_i %> hrs and <%=flt.duration % 60.to_i %> minutes
          </td>

          <td>
            <%= f.radio_button :flight_id, flt.id %>
          </td>
        
        </tr>
      <%end%>

  </tbody>
</table>

<div class="control">
  <%= f.submit "Select Flight", class: "button is-primary"%>
</div>

<%end%>

app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title">Flights</h1>


 
<%= simple_form_for :flight, url: root_path, method: "GET", local: true do |f| %>
    

  <div class="control">
    <label class="label">From</label>
    <div class="select">

      <%= f.input :from_airport_id, as: :select, 
      collection: @airport_options, required: false , wrapper: false, label: false%>
    </div>
  </div>
    

  <div class="control">
    <label class="label">To</label>
    <div class="select">

      <%= f.input :to_airport_id, as: :select,  
        collection: @airport_options, required: false , wrapper: false, label: false%>
    </div>
  </div> 

  <div class="control">
    <label class="label">Date</label>
    <div class="select">
      <%= f.input :takeoff, as: :select, collection: @date_options,
       required: false , wrapper: false, label: false, selected: @date_options.first%>
    </div>      
  </div>

  <div class="control">
    <label class="label">Number of passengers</label>
    <div class="select">
      <%= f.input :num_passenger, as: :select, collection: (1..4), selected: 1,
       required: true, wrapper: false, label: false%>
    </div>
  </div>

  <br>
  <div class="control">
    <%= f.submit "Search", class: "button is-primary"%>
  </div>
<% end %>

<% if @flights && @flights.empty?%>
  <p>Sorry, we cannot find a flight of your choosing. Please select another flight.</p>
<%elsif @flights%>
  <%= render 'results' %>

<%else%>
  <p>Please select at least one flight option</p>
<%end%>

app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Back', flights_path %>

app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_flight_path(@flight) %> |
<%= link_to 'Back', flights_path %>