config/routes.rb
Rails.application.routes.draw do
  resources :passengers
  resources :bookings
  resources :flights
  resources :charges do
    member do
      get 'success'
    end
  end

  root 'flights#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_one :charge
  has_many :passengers, dependent: :destroy
  accepts_nested_attributes_for :passengers, allow_destroy: true
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show edit update destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show; end

  # GET /bookings/new
  def new
    @booking = Booking.new
    booking_params.reject! { |_, v| v.blank? }
    @booking.flight = Flight.find(params[:booking][:flight_id])
    @booking.passengers.build
  end

  # GET /bookings/1/edit
  def edit; end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        PassengerMailer.with(booking_id: @booking.id).thank_you_email.deliver_later
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_booking
    @booking = Booking.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def booking_params
    params.require(:booking).permit(:flight_id, :num_passenger, passengers_attributes: %i[id first_name last_name email])
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_booking_card.html.erb
<p id="notice"><%= notice %></p>


<div class="card">
  <div class="card-image">
    <figure class="image is-2by1">
      <%= image_tag ("travel.jpg")%>
    </figure>
  </div>
  <div class="card-content">
    <% booking.passengers.each do |p|%>
      <div class="media">
        <div class="media-left">
          <figure class="image is-48x48">
            <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
          </figure>
        </div>
        <div class="media-content">
          <p class="title is-4"><%= p.first_name%> <%=p.last_name%></p>
          <p class="subtitle is-6"><%=p.email%></p>
        </div>
      </div>
    <%end%>

    <div class="content">
      From <%= booking.flight.from_airport.code%> to <%= booking.flight.to_airport.code %>
      <br>
      Take off
      <time datetime="2016-1-1"><%=booking.flight.takeoff%></time>

        
      <br>
      <%= booking.flight.duration / 60.to_i %> hours and <%=booking.flight.duration % 60.to_i%> minutes
      <br>
       
    </div>
  <div class="control">
  <button class="button is-warning">
    <%= link_to "Proceed to pay for tickets", new_charge_path(:booking_id=>booking.id) %>
  </button>
</div>      

  </div>

</div>

app/views/bookings/_form.html.erb
<%= form_with(model: booking) do |form| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
        <% booking.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<% @bookings.each do |booking| %>
  <%= render 'booking_card',  {booking: booking}%>
<% end %>

app/views/bookings/new.html.erb
<h1 class="title">New Booking</h1>

<%= form_with(model: @booking, local: true) do |f|%>
  <%= f.hidden_field :flight_id, value: params[:booking][:flight_id]%>
  <% params[:booking][:num_passenger].to_i.times do %>
    <h2 class="title">New Passenger<h2>
    <%= f.fields_for :passengers do |p| %>
      <div class="field">
        <%= p.label :first_name, 'Your Name' , class: "label"%>
        <div class="control">
          <%= p.text_field :first_name, class:"input", type:"text", placeholder:"e.g. Michael"%>
        </div>
      </div>

      <div class="field">
        <%= p.label :first_name, 'Lastname', class: "label" %>
        <div class="control">

          <%= p.text_field :last_name, class:"input", type:"text", placeholder: "e.g. Scott" %>
        </div>
      </div>

      <div class="field">
        <%=p.label :email, 'Email'%>
        <div class="control">
          <%= p.text_field :email, class:"input", type:"text", placeholder: "e.g. michael@dm.com" %>
        </div>
      </div>
    <%end%>

  <%end%>
  <div class="control">

    <%=f.submit 'Book',  class: "button is-primary"%>
  </div>
<%end%>

app/views/bookings/show.html.erb
      <%= render 'booking_card',  {booking: @booking}%>